version: "2.3"
services:
  # ROS eloquent

  maze_navigation:
    build:
        context: ../
        dockerfile: ./Dockerfile
    tty: true
    environment: 
      - "ROS_DOMAIN_ID=10"
      - "DISPLAY=$DISPLAY"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    network_mode: host
    pid: host
    command: ros2 launch maze_bringup navigation_maze.launch.py

  # ROS Noetic + ROS 2 eloquent
  bridge:
    image: ros:eloquent-ros1-bridge
    restart: on-failure
    tty: true
    network_mode: host
    pid: host
    environment:
      - "ROS_MASTER_URI=http://10.5.10.159:11311"
      - "ROS_IP=10.5.10.46"
      - "ROS_DOMAIN_ID=10"
    command: ros2 run ros1_bridge dynamic_bridge

