version: "2.3"
services:

  # ROS foxy - maze navigation
  maze_navigation:
    build:
        context: ../
        dockerfile: ./Dockerfile
    tty: true
    environment: 
      - DISPLAY=$DISPLAY
      - ROS_DOMAIN_ID=10
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./cyclonedds.xml:/cyclonedds.xml
      - ../maze_bringup/config/nav2_params.yaml:/ros2_ws/src/maze_bringup/config/nav2_params.yaml #testing nav2 params
      - ../maze_bringup/config/maze_cam.png:/ros2_ws/src/maze_bringup/config/maze_cam.png
    network_mode: service:husarnet  # This will put the Husarnet Client in the same network namespace as your app 
    command: 
      - bash
      - -c
      - |
        export CYCLONEDDS_URI=file:///cyclonedds.xml
        ros2 launch maze_bringup navigation_maze.launch.py
        
  husarnet:
    image: husarnet/husarnet
    restart: unless-stopped
    volumes:
      - /var/lib/husarnet  # This will persist your Husarnet Client keys, thus IP of the container will be stable/the same between (re)boots
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file: 
      - ./.env  # create .env file in the same folder as Dockerfile and specify HOSTNAME and JOINCODE there


